### ISSUE TITLE
What is the training platform and how long did the training take?

### ISSUE THREAD

**Issue by yanrihong** [lesjie-wen/tinyvla#3]
I have read your paper "TinyVLA: Towards Fast, Data-Efficient Vision-Language-Action Models for Robotic Manipulation" with great interest. The work presented is very impressive. I have a few questions regarding the training process:
1. What hardware platform was used for training the models (e.g., 4090, A100, etc.)?
2. How long did the training process take for each of the different model sizes (TinyVLA - S, B, H)?
Thank you for your time and for sharing your research. Looking forward to your response.

**Comment by cvpr25divla** [comment]
We use 8 x L40 for training.
The longest is TinyVLA-H, which maybe 40-50hrs in our experiments. But the specified time is despending on your data scale.
